server:
  port: 8081

spring:
  # 禁用MongoDB自动配置（暂时）
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  
  # 跨域配置
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# 日志配置
logging:
  level:
    root: INFO
    com.photo: DEBUG
    org.springframework.web: DEBUG

# JWT配置（简化）
jwt:
  secret: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
  expiration: 86400

# 百度文心一言配置（简化）
baidu:
  qianfan:
    api-key: bce-v3/ALTAK-DIc0sY4pIxIoeEdHUJ13Z/723d27efa69e7d0e2b032468bb3d88a221164170
    model: ernie-4.0-8k